# Generated by Django 2.2 on 2019-04-29 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('index', models.SmallIntegerField(unique=True)),
                ('path', models.ImageField(upload_to='img/Book')),
            ],
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateField(default=datetime.date(2019, 5, 29)),
        ),
    ]
