# Generated by Django 2.2 on 2019-04-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_auto_20190429_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotpic',
            name='path',
            field=models.ImageField(upload_to='Book'),
        ),
    ]
