# Generated by Django 2.2 on 2019-04-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_auto_20190429_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='UserImg')),
            ],
        ),
    ]
